// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/Worklist.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Work_WorkPriority int32

const (
	Work_LOW  Work_WorkPriority = 0
	Work_MID  Work_WorkPriority = 50
	Work_HIGH Work_WorkPriority = 100
)

// Enum value maps for Work_WorkPriority.
var (
	Work_WorkPriority_name = map[int32]string{
		0:   "LOW",
		50:  "MID",
		100: "HIGH",
	}
	Work_WorkPriority_value = map[string]int32{
		"LOW":  0,
		"MID":  50,
		"HIGH": 100,
	}
)

func (x Work_WorkPriority) Enum() *Work_WorkPriority {
	p := new(Work_WorkPriority)
	*p = x
	return p
}

func (x Work_WorkPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Work_WorkPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_Worklist_proto_enumTypes[0].Descriptor()
}

func (Work_WorkPriority) Type() protoreflect.EnumType {
	return &file_proto_Worklist_proto_enumTypes[0]
}

func (x Work_WorkPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Work_WorkPriority.Descriptor instead.
func (Work_WorkPriority) EnumDescriptor() ([]byte, []int) {
	return file_proto_Worklist_proto_rawDescGZIP(), []int{0, 0}
}

type Work_WorkStatus int32

const (
	Work_INACTIVE Work_WorkStatus = 0
	Work_ACTIVE   Work_WorkStatus = 1
)

// Enum value maps for Work_WorkStatus.
var (
	Work_WorkStatus_name = map[int32]string{
		0: "INACTIVE",
		1: "ACTIVE",
	}
	Work_WorkStatus_value = map[string]int32{
		"INACTIVE": 0,
		"ACTIVE":   1,
	}
)

func (x Work_WorkStatus) Enum() *Work_WorkStatus {
	p := new(Work_WorkStatus)
	*p = x
	return p
}

func (x Work_WorkStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Work_WorkStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_Worklist_proto_enumTypes[1].Descriptor()
}

func (Work_WorkStatus) Type() protoreflect.EnumType {
	return &file_proto_Worklist_proto_enumTypes[1]
}

func (x Work_WorkStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Work_WorkStatus.Descriptor instead.
func (Work_WorkStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_Worklist_proto_rawDescGZIP(), []int{0, 1}
}

type WorkList_WorkListStatus int32

const (
	WorkList_INACTIVE WorkList_WorkListStatus = 0
	WorkList_ACTIVE   WorkList_WorkListStatus = 1
)

// Enum value maps for WorkList_WorkListStatus.
var (
	WorkList_WorkListStatus_name = map[int32]string{
		0: "INACTIVE",
		1: "ACTIVE",
	}
	WorkList_WorkListStatus_value = map[string]int32{
		"INACTIVE": 0,
		"ACTIVE":   1,
	}
)

func (x WorkList_WorkListStatus) Enum() *WorkList_WorkListStatus {
	p := new(WorkList_WorkListStatus)
	*p = x
	return p
}

func (x WorkList_WorkListStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkList_WorkListStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_Worklist_proto_enumTypes[2].Descriptor()
}

func (WorkList_WorkListStatus) Type() protoreflect.EnumType {
	return &file_proto_Worklist_proto_enumTypes[2]
}

func (x WorkList_WorkListStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkList_WorkListStatus.Descriptor instead.
func (WorkList_WorkListStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_Worklist_proto_rawDescGZIP(), []int{1, 0}
}

type Work struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Priority   Work_WorkPriority `protobuf:"varint,3,opt,name=priority,proto3,enum=grpc.Work_WorkPriority" json:"priority,omitempty"`
	StatusWork Work_WorkStatus   `protobuf:"varint,5,opt,name=statusWork,proto3,enum=grpc.Work_WorkStatus" json:"statusWork,omitempty"`
}

func (x *Work) Reset() {
	*x = Work{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Worklist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Work) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Work) ProtoMessage() {}

func (x *Work) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Worklist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Work.ProtoReflect.Descriptor instead.
func (*Work) Descriptor() ([]byte, []int) {
	return file_proto_Worklist_proto_rawDescGZIP(), []int{0}
}

func (x *Work) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Work) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Work) GetPriority() Work_WorkPriority {
	if x != nil {
		return x.Priority
	}
	return Work_LOW
}

func (x *Work) GetStatusWork() Work_WorkStatus {
	if x != nil {
		return x.StatusWork
	}
	return Work_INACTIVE
}

type WorkList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status WorkList_WorkListStatus `protobuf:"varint,3,opt,name=status,proto3,enum=grpc.WorkList_WorkListStatus" json:"status,omitempty"`
	Works  []*Work                 `protobuf:"bytes,4,rep,name=works,proto3" json:"works,omitempty"`
}

func (x *WorkList) Reset() {
	*x = WorkList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Worklist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkList) ProtoMessage() {}

func (x *WorkList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Worklist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkList.ProtoReflect.Descriptor instead.
func (*WorkList) Descriptor() ([]byte, []int) {
	return file_proto_Worklist_proto_rawDescGZIP(), []int{1}
}

func (x *WorkList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkList) GetStatus() WorkList_WorkListStatus {
	if x != nil {
		return x.Status
	}
	return WorkList_INACTIVE
}

func (x *WorkList) GetWorks() []*Work {
	if x != nil {
		return x.Works
	}
	return nil
}

type InputRequestCreateListWork struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *InputRequestCreateListWork) Reset() {
	*x = InputRequestCreateListWork{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Worklist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputRequestCreateListWork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputRequestCreateListWork) ProtoMessage() {}

func (x *InputRequestCreateListWork) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Worklist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputRequestCreateListWork.ProtoReflect.Descriptor instead.
func (*InputRequestCreateListWork) Descriptor() ([]byte, []int) {
	return file_proto_Worklist_proto_rawDescGZIP(), []int{2}
}

func (x *InputRequestCreateListWork) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RequestWorkAssociateListWorks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewWork *Work  `protobuf:"bytes,1,opt,name=newWork,proto3" json:"newWork,omitempty"`
	IdList  string `protobuf:"bytes,2,opt,name=idList,proto3" json:"idList,omitempty"`
}

func (x *RequestWorkAssociateListWorks) Reset() {
	*x = RequestWorkAssociateListWorks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Worklist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestWorkAssociateListWorks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWorkAssociateListWorks) ProtoMessage() {}

func (x *RequestWorkAssociateListWorks) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Worklist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWorkAssociateListWorks.ProtoReflect.Descriptor instead.
func (*RequestWorkAssociateListWorks) Descriptor() ([]byte, []int) {
	return file_proto_Worklist_proto_rawDescGZIP(), []int{3}
}

func (x *RequestWorkAssociateListWorks) GetNewWork() *Work {
	if x != nil {
		return x.NewWork
	}
	return nil
}

func (x *RequestWorkAssociateListWorks) GetIdList() string {
	if x != nil {
		return x.IdList
	}
	return ""
}

type RequestCreateWork struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewWork *Work `protobuf:"bytes,1,opt,name=newWork,proto3" json:"newWork,omitempty"`
}

func (x *RequestCreateWork) Reset() {
	*x = RequestCreateWork{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Worklist_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestCreateWork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCreateWork) ProtoMessage() {}

func (x *RequestCreateWork) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Worklist_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCreateWork.ProtoReflect.Descriptor instead.
func (*RequestCreateWork) Descriptor() ([]byte, []int) {
	return file_proto_Worklist_proto_rawDescGZIP(), []int{4}
}

func (x *RequestCreateWork) GetNewWork() *Work {
	if x != nil {
		return x.NewWork
	}
	return nil
}

type RequestDeleteWork struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewWork string `protobuf:"bytes,1,opt,name=newWork,proto3" json:"newWork,omitempty"`
}

func (x *RequestDeleteWork) Reset() {
	*x = RequestDeleteWork{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Worklist_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDeleteWork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDeleteWork) ProtoMessage() {}

func (x *RequestDeleteWork) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Worklist_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDeleteWork.ProtoReflect.Descriptor instead.
func (*RequestDeleteWork) Descriptor() ([]byte, []int) {
	return file_proto_Worklist_proto_rawDescGZIP(), []int{5}
}

func (x *RequestDeleteWork) GetNewWork() string {
	if x != nil {
		return x.NewWork
	}
	return ""
}

type ResponseWorkList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListWorks []*WorkList `protobuf:"bytes,1,rep,name=listWorks,proto3" json:"listWorks,omitempty"`
}

func (x *ResponseWorkList) Reset() {
	*x = ResponseWorkList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Worklist_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseWorkList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseWorkList) ProtoMessage() {}

func (x *ResponseWorkList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Worklist_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseWorkList.ProtoReflect.Descriptor instead.
func (*ResponseWorkList) Descriptor() ([]byte, []int) {
	return file_proto_Worklist_proto_rawDescGZIP(), []int{6}
}

func (x *ResponseWorkList) GetListWorks() []*WorkList {
	if x != nil {
		return x.ListWorks
	}
	return nil
}

var File_proto_Worklist_proto protoreflect.FileDescriptor

var file_proto_Worklist_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x69, 0x73, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xea, 0x01, 0x0a, 0x04, 0x57, 0x6f,
	0x72, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69,
	0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x57, 0x6f, 0x72, 0x6b, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74,
	0x79, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x35, 0x0a, 0x0a, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x57, 0x6f, 0x72, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x2e, 0x57, 0x6f, 0x72, 0x6b,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x57, 0x6f,
	0x72, 0x6b, 0x22, 0x2a, 0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x6b, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69,
	0x74, 0x79, 0x12, 0x07, 0x0a, 0x03, 0x4c, 0x4f, 0x57, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x4d,
	0x49, 0x44, 0x10, 0x32, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x49, 0x47, 0x48, 0x10, 0x64, 0x22, 0x26,
	0x0a, 0x0a, 0x57, 0x6f, 0x72, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0c, 0x0a, 0x08,
	0x49, 0x4e, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43,
	0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x22, 0xb3, 0x01, 0x0a, 0x08, 0x57, 0x6f, 0x72, 0x6b, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x57,
	0x6f, 0x72, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20,
	0x0a, 0x05, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x05, 0x77, 0x6f, 0x72, 0x6b, 0x73,
	0x22, 0x2a, 0x0a, 0x0e, 0x57, 0x6f, 0x72, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x22, 0x30, 0x0a, 0x1a,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x5d,
	0x0a, 0x1d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x41, 0x73, 0x73,
	0x6f, 0x63, 0x69, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x12,
	0x24, 0x0a, 0x07, 0x6e, 0x65, 0x77, 0x57, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x07, 0x6e, 0x65,
	0x77, 0x57, 0x6f, 0x72, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x39, 0x0a,
	0x11, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f,
	0x72, 0x6b, 0x12, 0x24, 0x0a, 0x07, 0x6e, 0x65, 0x77, 0x57, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x52,
	0x07, 0x6e, 0x65, 0x77, 0x57, 0x6f, 0x72, 0x6b, 0x22, 0x2d, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x12, 0x18, 0x0a,
	0x07, 0x6e, 0x65, 0x77, 0x57, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6e, 0x65, 0x77, 0x57, 0x6f, 0x72, 0x6b, 0x22, 0x40, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x09, 0x6c,
	0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x09,
	0x6c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x32, 0xe6, 0x02, 0x0a, 0x0f, 0x77, 0x6f,
	0x72, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a,
	0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x12,
	0x20, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72,
	0x6b, 0x1a, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x54, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x4f,
	0x66, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x12, 0x23, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x41, 0x73, 0x73,
	0x6f, 0x63, 0x69, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3d, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x57, 0x6f, 0x72, 0x6b, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3d, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x57, 0x6f, 0x72, 0x6b, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3b, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72,
	0x6b, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x4c, 0x69,
	0x73, 0x74, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x4d, 0x61, 0x72, 0x63, 0x65, 0x6c, 0x6f, 0x42, 0x61, 0x65, 0x7a, 0x61, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2d, 0x74, 0x65, 0x73, 0x74, 0x2d, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x69, 0x73, 0x74,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_Worklist_proto_rawDescOnce sync.Once
	file_proto_Worklist_proto_rawDescData = file_proto_Worklist_proto_rawDesc
)

func file_proto_Worklist_proto_rawDescGZIP() []byte {
	file_proto_Worklist_proto_rawDescOnce.Do(func() {
		file_proto_Worklist_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_Worklist_proto_rawDescData)
	})
	return file_proto_Worklist_proto_rawDescData
}

var file_proto_Worklist_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_Worklist_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_Worklist_proto_goTypes = []interface{}{
	(Work_WorkPriority)(0),                // 0: grpc.Work.WorkPriority
	(Work_WorkStatus)(0),                  // 1: grpc.Work.WorkStatus
	(WorkList_WorkListStatus)(0),          // 2: grpc.WorkList.WorkListStatus
	(*Work)(nil),                          // 3: grpc.Work
	(*WorkList)(nil),                      // 4: grpc.WorkList
	(*InputRequestCreateListWork)(nil),    // 5: grpc.InputRequestCreateListWork
	(*RequestWorkAssociateListWorks)(nil), // 6: grpc.RequestWorkAssociateListWorks
	(*RequestCreateWork)(nil),             // 7: grpc.RequestCreateWork
	(*RequestDeleteWork)(nil),             // 8: grpc.RequestDeleteWork
	(*ResponseWorkList)(nil),              // 9: grpc.ResponseWorkList
	(*emptypb.Empty)(nil),                 // 10: google.protobuf.Empty
}
var file_proto_Worklist_proto_depIdxs = []int32{
	0,  // 0: grpc.Work.priority:type_name -> grpc.Work.WorkPriority
	1,  // 1: grpc.Work.statusWork:type_name -> grpc.Work.WorkStatus
	2,  // 2: grpc.WorkList.status:type_name -> grpc.WorkList.WorkListStatus
	3,  // 3: grpc.WorkList.works:type_name -> grpc.Work
	3,  // 4: grpc.RequestWorkAssociateListWorks.newWork:type_name -> grpc.Work
	3,  // 5: grpc.RequestCreateWork.newWork:type_name -> grpc.Work
	4,  // 6: grpc.ResponseWorkList.listWorks:type_name -> grpc.WorkList
	5,  // 7: grpc.worklistService.CreateListWork:input_type -> grpc.InputRequestCreateListWork
	6,  // 8: grpc.worklistService.CreateWorkOfListWorks:input_type -> grpc.RequestWorkAssociateListWorks
	7,  // 9: grpc.worklistService.CreateWork:input_type -> grpc.RequestCreateWork
	8,  // 10: grpc.worklistService.DeleteWork:input_type -> grpc.RequestDeleteWork
	10, // 11: grpc.worklistService.ListWorks:input_type -> google.protobuf.Empty
	4,  // 12: grpc.worklistService.CreateListWork:output_type -> grpc.WorkList
	10, // 13: grpc.worklistService.CreateWorkOfListWorks:output_type -> google.protobuf.Empty
	10, // 14: grpc.worklistService.CreateWork:output_type -> google.protobuf.Empty
	10, // 15: grpc.worklistService.DeleteWork:output_type -> google.protobuf.Empty
	9,  // 16: grpc.worklistService.ListWorks:output_type -> grpc.ResponseWorkList
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_Worklist_proto_init() }
func file_proto_Worklist_proto_init() {
	if File_proto_Worklist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_Worklist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Work); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Worklist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Worklist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InputRequestCreateListWork); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Worklist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestWorkAssociateListWorks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Worklist_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestCreateWork); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Worklist_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestDeleteWork); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Worklist_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseWorkList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_Worklist_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_Worklist_proto_goTypes,
		DependencyIndexes: file_proto_Worklist_proto_depIdxs,
		EnumInfos:         file_proto_Worklist_proto_enumTypes,
		MessageInfos:      file_proto_Worklist_proto_msgTypes,
	}.Build()
	File_proto_Worklist_proto = out.File
	file_proto_Worklist_proto_rawDesc = nil
	file_proto_Worklist_proto_goTypes = nil
	file_proto_Worklist_proto_depIdxs = nil
}
